solufa/axios-mock-server

__tests__/index.spec.ts, src/AsyncNedb.ts, src/index.ts
=> fix: url params

.circleci/config.yml
[CircleCI](https://circleci.com/) の設定ファイルを追加しました。
- `git push` のたびにテストを実行します。
- 毎週日曜午前 9 時に `npm audit` を実行します。
=> ci: add configuration file of CircleCI

tsconfig.json
`npm run build` で型定義ファイルを書き出す設定を追加しました。
=> build: enable generation of '.d.ts'

__tests__/index.spec.ts, src/index.ts
=> feat(change): response of HTTP methods

__tests__/index.spec.ts, __tests__/libs/formToBuffer.ts, src/DataStore.ts, src/index.ts
=> feat(main): change function to class

.versionrc.json, CHANGELOG.md
Git のタグの運用が間違っていたため重複して書き出されていた行を削除しました。
また、 `feat:`, `fix:` 以外に `docs:`, `perf:`, `refactor:`, `test:` のプレフィックスがあるコミットメッセージも `CHANGELOG.md` に書き出すように [standard-version](https://www.npmjs.com/package/standard-version) の設定ファイルを追加しました。
=>  docs: fix CHANGELOG.md

bin/index.js, package-lock.json, package.json, src/lib/cli.ts
[minimist](https://www.npmjs.com/package/minimist) を利用して CLI で渡された引数の処理を追加しました。  
以下の手順で `--version` または `-v` を渡すとバージョンを表示します。
```sh
$ npm run build
$ node bin/index.js -v
```
または
```sh
$ node_modules/.bin/ts-node -e "require('./src/lib/cli').default(require('./package').version)" - -v
```
=> feat(cli): add command line arguments parser

.dependabot/config.yml
[Dependabot](https://dependabot.com/) のオートマージがうまく動作していないため、更新スケジュールを変更しました。
=> chore: change the update schedule from daily to live

README.md, __tests__/index.spec.ts, package-lock.json, package.json, src/AsyncNedb.ts, src/index.ts, src/lib/cli.ts, src/lib/createRouteString.ts, src/lib/getConfig.ts, src/lib/listFiles.ts, src/lib/replacePathSepIfWindows.ts
=> feat(CLI): add 'watch' and 'build'

CHANGELOG.md, README.md, __tests__/index.spec.ts, package-lock.json, package.json, src/AsyncNedb.ts, src/index.ts, src/lib/cli.ts, src/lib/createRouteString.ts, src/lib/getConfig.ts, src/lib/listFiles.ts, src/lib/replacePathSepIfWindows.ts
=> chore(release): 0.3.0

README.md, __tests__/index.spec.ts, src/index.ts, src/lib/cli.ts, src/lib/createRouteString.ts, src/lib/getConfig.ts
=> feat(CLI): add outputExt to config

CHANGELOG.md, README.md, __tests__/index.spec.ts, package-lock.json, package.json, src/index.ts, src/lib/cli.ts, src/lib/createRouteString.ts, src/lib/getConfig.ts
=> chore(release): 0.4.0

package-lock.json, package.json, src/adapter/index.ts, src/adapter/settle.d.ts, src/adapter/utils.ts, src/index.ts, src/lib/getConfig.ts
=> feat(main): delete axios-mock-adapter

src/lib/createRouteString.ts
=> fix(CLI): change path '/aaa/index.js' to '/aaa'

CHANGELOG.md, package-lock.json, package.json, src/lib/createRouteString.ts
=> chore(release): 0.8.1

.circleci/config.yml, .huskyrc, .lintstagedrc, commitlint.config.js, package-lock.json, package.json
* 型をチェックする npm run-script を追加
* コミットメッセージに Lint を実行
* `package-lock.json` を生成し直してアップデート
- npm version: `6.11.3`
=> chore: update npm scripts

.circleci/config.yml, .huskyrc, .lintstagedrc, CHANGELOG.md, __tests__/index.spec.ts, commitlint.config.js, lint-staged.config.js, package-lock.json, package.json, src/MockServer.ts
=> chore(release): 0.9.0

__tests__/units.spec.ts, src/findAndCallHandler.ts
=> chore(lint): add comments of eslint-disable

__tests__/index.spec.ts, __tests__/units.spec.ts
=> chore(test): add put and delete methods

__tests__/index.spec.ts
=> chore(test): add async methods

__tests__/index.spec.ts
=> chore(test): add throwing error

__tests__/units.spec.ts, src/createRelativePath.ts
=> chore(test): add condition to createRelativePath

__tests__/units.spec.ts
=> test: add case of method is undefined

CHANGELOG.md, __tests__/index.spec.ts, __tests__/units.spec.ts, package-lock.json, package.json, src/MockServer.ts, src/compositeParams.ts, src/createLogString.ts, src/createRelativePath.ts, src/createValues.ts, src/findAndCallHandler.ts, src/findHandler.ts, src/index.ts, src/makeResponse.ts, src/types.ts
=> chore(release): 0.10.0

README.md, docs/ja/README.md, examples/browser/webpack.config.js, examples/with-nuxtjs/README.md, examples/with-nuxtjs/jsconfig.json, examples/with-nuxtjs/mocks/users/_userId.js, examples/with-nuxtjs/nuxt.config.js, examples/with-nuxtjs/package.json, examples/with-nuxtjs/pages/index.vue, examples/with-nuxtjs/plugins/mock.js
[Nuxt.js](https://nuxtjs.org/) と合わせて axios-mock-server 使用する example を追加
[Nuxt.js](https://nuxtjs.org/) と合わせて使用する `examples/with-nuxtjs` を追加しました。  
また、以下のコードを修正しました。
- `README.md` で `enableLog()`, `disableLog()` の [axios](https://github.com/axios/axios) の処理に `await` を追加
- `examples/browser` の [webpack](https://webpack.js.org/) の監視の設定を修正  
\*[webpack](https://webpack.js.org/)  と axios-mock-server で 2 回ビルドが走らないように `watchOptions.ignored` を設定していましたが、モックの変更が HMR で反映されないため削除しました。
=> chore(examples): add and fix examples

src/lib/createRouteString.ts
=> chore(cli): fix import path string

examples/with-nuxtjs/plugins/mock.js
=> chore(example): delete app from nuxt plugin

CHANGELOG.md, README.md, __tests__/index.spec.ts, __tests__/units.spec.ts, docs/ja/README.md, examples/with-nuxtjs/plugins/mock.js, package-lock.json, package.json, src/MockServer.ts, src/createLogString.ts, src/createRelativePath.ts, src/findAndCallHandler.ts
=> chore(release): 0.12.0

__tests__/index.spec.ts, src/lib/buildRouteFile.ts, src/lib/cli.ts, src/lib/watchInputDir.ts, src/lib/writeRouteFile.ts, src/makeResponse.ts
=> fix copy response data

CHANGELOG.md, __tests__/index.spec.ts, package-lock.json, package.json, src/lib/buildRouteFile.ts, src/lib/cli.ts, src/lib/watchInputDir.ts, src/lib/writeRouteFile.ts, src/makeResponse.ts
=> chore(release): 0.12.1

examples/browser/src/index.js, examples/node/src/index.js, examples/with-nuxtjs/plugins/mock.js, examples/with-typescript/src/index.ts, src/lib/buildRouteFile.ts, src/lib/createRouteString.ts, src/lib/getConfig.ts, src/lib/watchInputDir.ts
=> feat(cli): change $route -> $mock

src/lib/buildRouteFile.ts, src/lib/getConfig.ts, src/lib/listFiles.ts
=> chore(cli): clarify codes

CHANGELOG.md, __tests__/index.spec.ts, __tests__/units.spec.ts, package-lock.json, package.json, src/compositeParams.ts, src/createLogString.ts, src/untransformData.ts, tsconfig.json
=> chore(release): 0.13.1

tsconfig.json
=> chore(main): delete unnecessary configs

package-lock.json, package.json
=> refactor(axios): move to devDependencies

CHANGELOG.md, __tests__/lib/index.spec.ts, __tests__/mocks/$mock.js, __tests__/mocks/$mock.ts, __tests__/mocks/index.ts, __tests__/mocks/users/_userId.ts, __tests__/mocks/users/index.ts, __tests__/mocks/users/self.ts, jest.config.js, package-lock.json, package.json, src/lib/buildRouteFile.ts, src/lib/createRouteString.ts, src/lib/dev.ts, src/lib/listFiles.ts, src/lib/replacePathSepIfWindows.ts, tsconfig.json
=> chore(release): 0.13.2

__tests__/index.spec.ts, __tests__/mocks/$mock.js, __tests__/mocks/$mock.ts, __tests__/mocks/collections/entries.json.ts
=> chore: add file extension tests

CHANGELOG.md, README.md, __tests__/index.spec.ts, __tests__/mocks/$mock.js, __tests__/mocks/$mock.ts, __tests__/mocks/collections/entries.json.ts, docs/ja/README.md, package-lock.json, package.json, src/MockServer.ts, src/lib/getConfig.ts
=> chore(release): 0.14.0

CHANGELOG.md, __tests__/index.spec.ts, __tests__/units.spec.ts, package-lock.json, package.json, src/compositeParams.ts, src/createLogString.ts, src/index.ts, src/untransformData.ts, tsconfig.json
=> chore(release): 0.14.1

__tests__/lib/index.spec.ts, __tests__/lib/mocks/$mock.js, __tests__/lib/mocks/$mock.ts, src/MockServer.ts, src/lib/buildRouteFile.ts, src/lib/cli.ts, src/lib/createRouteString.ts
=> feat(cli): add baseURL

CHANGELOG.md, __tests__/lib/index.spec.ts, __tests__/lib/mocks/$mock.js, __tests__/lib/mocks/$mock.ts, package-lock.json, package.json, src/MockServer.ts, src/lib/buildRouteFile.ts, src/lib/cli.ts, src/lib/createRouteString.ts
=> chore(release): 0.16.0

src/index.ts
=> fix(factory): add baseURL

CHANGELOG.md, package-lock.json, package.json, src/index.ts
=> chore(release): 0.16.1

src/lib/buildRouteFile.ts
=> fix(cli): ignore files other than js and ts

src/lib/buildRouteFile.ts
=> fix: ignore empty file

CHANGELOG.md, package-lock.json, package.json, src/lib/buildRouteFile.ts
=> chore(release): 0.16.3

CHANGELOG.md, package.json, src/makeResponse.ts
=> chore(release): 0.17.1

CHANGELOG.md, package.json, src/lib/cli.ts, src/lib/writeRouteFile.ts, tsconfig.json
=> chore(release): 0.17.2

CHANGELOG.md, README.md, __tests__/lib/index.spec.ts, docs/ja/README.md, package.json, src/lib/cli.ts, yarn.lock
=> chore(release): 0.18.0

CHANGELOG.md, __tests__/lib/index.spec.ts, package.json, src/lib/cli.ts
=> chore(release): 0.18.1

.github/workflows/nodejs.yml, CHANGELOG.md, README.md, __tests__/index.spec.ts, __tests__/lib/index.spec.ts, docs/ja/README.md, package.json, src/lib/buildRouteFile.ts, src/lib/cli.ts, src/lib/getConfig.ts, yarn.lock
=> chore(release): 0.19.0
